// src/lib/Counter.svelte
<script lang="ts">
  import type { FrameworkData } from "../server/types";

  type Props = {
    count: number;
    date: string;
    framework: FrameworkData;
  };

  export let data: Props;
</script>

<div class="flex flex-col text-center text-xl space-y-8 mx-4">
  <p>It's been</p>
  <p class="font-bold text-9xl">{data.count}</p>
  <p>day(s) since the latest JavaScript framework.</p>
  <div class="flex w-full text-sm">
    <p class="w-full text-center">
      Last JS framework:
      <a
        href={data.framework.link}
        class="hover:underline text-blue-800"
        target="_blank"
        rel="noreferrer noopenener">{data.framework.name}</a
      >
      released on {data.date}
    </p>
  </div>
</div>

// src/components/Counter.tsx
import { type FrameworkData } from "~/server/types";

type Props = {
  count: number;
  date: string;
  framework: FrameworkData;
};

export default function Counter(props: Props) {
  const linkHref = props.framework.link ?? props.framework.releaseLink ?? "";

  return (
    <div className="mx-4 flex flex-col space-y-8 text-center text-xl">
      <p>It&apos;s been</p>
      <p className="text-9xl font-bold">{props.count}</p>
      <p>day(s) since the latest JavaScript framework.</p>
      <div className="flex w-full text-sm">
        <p className="w-full text-center">
          Last JS framework:
          <a
            href={linkHref}
            className="text-blue-800 hover:underline"
            target="_blank"
            rel="noreferrer noopenener"
          >
            {props.framework.name}
          </a>
          released on {props.date}
        </p>
      </div>
    </div>
  );
}
