// src/lib/Footer.svelte
<footer class="text-sm text-center py-8 w-full px-4">
  <div>
    You think the data is wrong? File an issue <a
      href={"https://github.com/cuvar/days-since-js-framework/issues"}
      class="hover:underline text-blue-800"
      target="_blank"
      rel="noreferrer noopenener">here</a
    >!
  </div>
</footer>

// src/components/Footer.tsx
export default function Footer() {
  return (
    <footer className="w-full px-4 py-8 text-center text-sm">
      <div>
        You think the data is wrong? File an issue{" "}
        <a
          href={"https://github.com/cuvar/days-since-js-framework/issues"}
          className="text-blue-800 hover:underline"
          target="_blank"
          rel="noreferrer noopenener"
        >
          here
        </a>
        !
      </div>
    </footer>
  );
}
